version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp_web
    ports:
      - "85:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: api_teste
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api_teste
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scriptTables.sql:/docker-entrypoint-initdb.d/scriptTables.sql

volumes:
  db_data:
